#!/usr/bin/env bash
set -euo pipefail

ENV_DIR="${HOME}/.ironclaw"
ENV_FILE="${ENV_DIR}/.env"

mkdir -p "${ENV_DIR}"
umask 077
: > "${ENV_FILE}"

write_env() {
  local key="$1"
  local value="${!key-}"

  if [ -z "$value" ]; then
    return
  fi

  value="${value//\\/\\\\}"
  value="${value//\"/\\\"}"
  value="${value//$'\n'/\\n}"

  printf '%s="%s"\n' "$key" "$value" >> "${ENV_FILE}"
}

vars=(
  DATABASE_URL
  DATABASE_POOL_SIZE
  SECRETS_MASTER_KEY
  ONBOARD_COMPLETED
  IRONCLAW_IN_DOCKER
  RUST_LOG

  GATEWAY_ENABLED
  GATEWAY_HOST
  GATEWAY_PORT
  GATEWAY_AUTH_TOKEN
  HTTP_HOST
  HTTP_PORT
  HTTP_WEBHOOK_SECRET

  SANDBOX_ENABLED

  LLM_BACKEND
  LLM_REQUEST_TIMEOUT_SECS

  EMBEDDINGS_PROVIDER
  EMBEDDINGS_MODEL

  NEARAI_API_KEY
  NEARAI_MODEL
  NEARAI_BASE_URL
  NEARAI_AUTH_URL
  NEARAI_SESSION_TOKEN
  NEARAI_SESSION_PATH
  NEARAI_FALLBACK_MODEL
  NEARAI_MAX_RETRIES

  LLM_MODEL
  LLM_BASE_URL
  LLM_API_KEY
  LLM_EXTRA_HEADERS

  OPENAI_API_KEY
  OPENAI_MODEL
  OPENAI_BASE_URL
  LLM_USE_CODEX_AUTH
  CODEX_AUTH_PATH

  ANTHROPIC_API_KEY
  ANTHROPIC_OAUTH_TOKEN
  ANTHROPIC_MODEL
  ANTHROPIC_BASE_URL
  ANTHROPIC_CACHE_RETENTION

  OLLAMA_MODEL
  OLLAMA_BASE_URL

  MINIMAX_API_KEY
  MINIMAX_MODEL
  MINIMAX_BASE_URL

  GITHUB_COPILOT_TOKEN
  GITHUB_COPILOT_MODEL
  GITHUB_COPILOT_EXTRA_HEADERS

  OPENAI_CODEX_MODEL
  OPENAI_CODEX_CLIENT_ID
  OPENAI_CODEX_AUTH_URL
  OPENAI_CODEX_API_URL

  GEMINI_API_KEY
  GEMINI_MODEL
  GEMINI_CREDENTIALS_PATH
  GEMINI_API_KEY_AUTH_MECHANISM
  GEMINI_SAFETY_BLOCK_NONE
  GEMINI_CLI_CUSTOM_HEADERS
  GEMINI_TOP_P
  GEMINI_TOP_K
  GEMINI_SEED
  GEMINI_PRESENCE_PENALTY
  GEMINI_FREQUENCY_PENALTY
  GEMINI_RESPONSE_MIME_TYPE
  GEMINI_RESPONSE_JSON_SCHEMA
  GEMINI_CACHED_CONTENT

  CIRCUIT_BREAKER_THRESHOLD
  CIRCUIT_BREAKER_RECOVERY_SECS
  RESPONSE_CACHE_ENABLED
  RESPONSE_CACHE_TTL_SECS
  RESPONSE_CACHE_MAX_ENTRIES
)

for key in "${vars[@]}"; do
  write_env "$key"
done

chmod 600 "${ENV_FILE}"

exec ironclaw
