#!/usr/bin/env bash
set -euo pipefail

mkdir -p "${HOME}/.ironclaw"
umask 077

cat > "${HOME}/.ironclaw/.env" <<EOF
DATABASE_URL=${DATABASE_URL:-}
LLM_BACKEND=${LLM_BACKEND:-openai}
OPENAI_API_KEY=${OPENAI_API_KEY:-}
SECRETS_MASTER_KEY=${SECRETS_MASTER_KEY:-}
SANDBOX_ENABLED=${SANDBOX_ENABLED:-false}
ONBOARD_COMPLETED=${ONBOARD_COMPLETED:-true}

GATEWAY_ENABLED=${GATEWAY_ENABLED:-true}
GATEWAY_HOST=${GATEWAY_HOST:-0.0.0.0}
GATEWAY_PORT=${GATEWAY_PORT:-3000}
GATEWAY_AUTH_TOKEN=${GATEWAY_AUTH_TOKEN:-}

HTTP_HOST=${HTTP_HOST:-0.0.0.0}
HTTP_PORT=${HTTP_PORT:-8080}
HTTP_WEBHOOK_SECRET=${HTTP_WEBHOOK_SECRET:-}

IRONCLAW_IN_DOCKER=${IRONCLAW_IN_DOCKER:-true}
RUST_LOG=${RUST_LOG:-ironclaw=info}
EOF

chmod 600 "${HOME}/.ironclaw/.env"

exec ironclaw
